name: Appointments Microservice CI/CD
on:
  push:
    paths:
      - 'appointments/**'  # Path to the appointments microservice
  pull_request:
    paths:
      - 'appointments/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: fakhiha
          password: ${{ secrets.Siriusbetelgeuse6545 }}

      - name: Build and Push Docker Image - Appointments
        run: |
          docker build -t fakhiha/appointments:${{ github.sha }} ./appointments
          docker push fakhiha/appointments:${{ github.sha }}
