name: Appointments Microservice CI/CD
on:
  push:
    paths:
      - 'appointments/**'  # Path to the appointments microservice
  pull_request:
    paths:
      - 'appointments/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Other steps to build and push Docker image...

      - name: Update Docker Compose File - Appointments
        run: |
          sed -i 's|appointments-image:old-tag|appointments-image:new-tag|g' docker-compose.yml
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add docker-compose.yml
          git commit -m "Update Appointments image tag in Docker Compose"
          git push origin main
