name: Doctors Microservice CI/CD
on:
  push:
    paths:
      - 'doctor/**'  # Path to the doctors microservice
  pull_request:
    paths:
      - 'doctor/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: fakhiha
          password: ${{ secrets.Siriusbetelgeuse6545 }}

      - name: Build and Push Docker Image - Doctors
        run: |
          docker build -t fakhiha/doctors:${{ github.sha }} ./doctor
          docker push fakhiha/doctors:${{ github.sha }}
