name: Doctors Microservice CI/CD
on:
  push:
    paths:
      - 'doctor/**'  # Path to the doctors microservice
  pull_request:
    paths:
      - 'doctor/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Other steps to build and push Docker image...

      - name: Update Docker Compose File - Doctors
        run: |
          sed -i 's|doctors-image:old-tag|doctors-image:new-tag|g' docker-compose.yml
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add docker-compose.yml
          git commit -m "Update Doctors image tag in Docker Compose"
          git push origin main
