name: Frontend Microservice CI/CD
on:
  push:
    paths:
      - 'frontend/**'  # Path to the frontend microservice
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: fakhiha
          password: ${{ secrets.Siriusbetelgeuse6545 }}

      - name: Build and Push Docker Image - Frontend
        run: |
          docker build -t fakhiha/frontend:${{ github.sha }} ./frontend
          docker push fakhiha/frontend:${{ github.sha }}
