name: Frontend Microservice CI/CD
on:
  push:
    paths:
      - 'frontend/**'  # Path to the frontend microservice
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Other steps to build and push Docker image...

      - name: Update Docker Compose File - Frontend
        run: |
          sed -i 's|frontend-image:old-tag|frontend-image:new-tag|g' docker-compose.yml
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add docker-compose.yml
          git commit -m "Update Frontend image tag in Docker Compose"
          git push origin main
